name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: habinook
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Install devenv.sh
        run: devenv shell

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test

      - name: Run a single command in the devenv shell
        run: devenv shell hello