name: Code quality

on:
  push:
    branches: [main]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "experimental-features = nix-command flakes"

      - name: Use Cachix
        uses: cachix/cachix-action@v16
        with:
          name: habinook
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Cache Biome
        uses: actions/cache@v4
        with:
          path: ~/.cache/biome
          key: biome-${{ runner.os }}-${{ hashFiles('**/*.{ts,tsx,js,json}') }}
          restore-keys: biome-${{ runner.os }}-

      - name: Run Nix Flake Check
        run: nix flake check

      - name: Run Biome
        run: nix run .#biome -- ci . --cache --max-diagnostics=0
