name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Устанавливаем Nix
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      # Включаем Cachix
      - uses: cachix/cachix-action@v16
        with:
          name: habinook
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Запускаем сборку devShell
      - name: Build devenv
        run: devenv shell
