name: "Test"
on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: habinook
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          push: true

      # Проверка flake
      - run: nix flake check

      # Запуск devShell (твой существующий devShell.default)
      - run: nix develop .#default -c echo "OK"
