name: Code quality

on:
  push:
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: "experimental-features = nix-command flakes"
      - name: Run Nix Flake Check
        run: nix flake check
      - name: Run Biome
        run: nix develop --command bash -c "pnpm install && pnpm biome ci ."